### PR TITLE
fixed logic errors in config validation

### PR DESCRIPTION
**Pull request by mleotta**
It turns out some of the logic was wrong in the recently merged branch on configuration validation

### CODE REVIEW

**Review by dstoup — APPROVED** [review]
LGTM

**Review by russelldj — APPROVED** [review]

**Comment by mleotta** [comment]
Jenkins test this please

**Comment by mleotta** [comment]
Any idea what happened to the CI on this branch?  It says the Windows build is still pending, but there is a message saying the Windows build succeeded.  Can we merge?

**Comment by russelldj** [comment]
Unfortunately I have no idea about CI. However, I noticed this doesn't contain either `validate_optional_input_dir` or `validate_required_input_dir`. Was this intentional? If not, should it be included in this commit?

**Comment by mleotta** [comment]
Good point on the missing input directory variants.  I should have add them previously, but we didn't have an applet that need input directories, so I guess that's why I didn't add them.  However, we do have a need for this case.  I'd rather add it in a new PR because this PR is about fixing logic bugs in the functions that we already merged.

**Comment by linus-sherrill** [comment]
Sometimes CI gets stuck. In this case, there is an entry that the Windows build succeeded and that overrides what is in the summary list.

**Pull request merged**
