### PR TITLE
Add descriptor set C and Python bindings

### PR DESCRIPTION
**Pull request by Purg**
Plus:
- Some other doc-string additions.
- Removed a VITAL_C_EXPORT from a function implementation in a cxx file (not needed/used there).

### CODE REVIEW

**Comment by Purg** [comment]
PTAL @linus-sherrill @mleotta

**Comment by hughed2** [comment]
Can one of the admins verify this patch?

**Comment by hughed2** [comment]
Can one of the admins verify this patch?

**Comment by Purg** [comment]
Rebased on hackathon/master.

**Comment by Purg** [comment]
Oops, missed some CMakeLists.txt changes.

**Pull request merged**
