### PR TITLE
Default python version to 3

### PR DESCRIPTION
**Pull request by dstoup**

### CODE REVIEW

**Comment by linus-sherrill** [comment]
Jenkins test this please

**Comment by dstoup** [comment]
I had some issues with the same test when I tried this a few months ago. I'm not python smart enough to understand the issue though.

624 - test-python-pymodules-pythonpath (Failed)

**Comment by linus-sherrill** [comment]
Jenkins test this please

**Comment by dstoup** [comment]
Very strange. The failing test here is the same as the failing test when I make python 3 the default version. I suspect there is something not right about this test that it would fail when things like these are changed. Trouble is, I have no idea what's going on in that test so I'm not going to be of much use beyond this comment.

**Pull request closed without merging**
