### PR TITLE
Allow "downsampler" to work on input with missing frames

### PR DESCRIPTION
**Pull request by neal-siekierski**
This PR contains changes to allow `downsampler_process` to work on input that's missing frames by using the provided timestamp to determine the elapsed time. For cases when a timestamp is missing, the code assumes the provided frame rate. It doesn't use it otherwise.

I wasn't sure how to have this interact with the burst mode when there's such a large gap that a down-sampled output would be missed. I chose to have it count the missed output as well. (Normally, at say 5Hz output and a 3/2 cycle, you'd have outputs at 0s, 0.2s, 0.4s, 1s, 1.2s, 1.4s, etc. I've implemented it such that if there is no input around e.g. 1.2s, that output is missed but continues as normal, thus 1s, ~1.2s~, 1.4s, 2s, 2.2s, 2.4s, etc.)

Let me know if this should be against another branch. Once it's finalized, I can update #690 and add this to it.

Here is an extract from a log I made of output time stamps from a test video from @mattdawkins with a nominal ~30Hz frame rate but with many single missing frames and down-sampled to 5Hz:
```
ts(f: 13570, t: 770633333 (Wed Dec 31 19:12:50 1969), d: 0)
ts(f: 13573, t: 770800000 (Wed Dec 31 19:12:50 1969), d: 0)
ts(f: 13576, t: 771000000 (Wed Dec 31 19:12:51 1969), d: 0)
ts(f: 13581, t: 771266666 (Wed Dec 31 19:12:51 1969), d: 0)
ts(f: 13583, t: 771400000 (Wed Dec 31 19:12:51 1969), d: 0)
ts(f: 13587, t: 771633333 (Wed Dec 31 19:12:51 1969), d: 0)
ts(f: 13590, t: 771800000 (Wed Dec 31 19:12:51 1969), d: 0)
ts(f: 13594, t: 772000000 (Wed Dec 31 19:12:52 1969), d: 0)
ts(f: 13599, t: 772266666 (Wed Dec 31 19:12:52 1969), d: 0)
ts(f: 13601, t: 772400000 (Wed Dec 31 19:12:52 1969), d: 0)
ts(f: 13606, t: 772633333 (Wed Dec 31 19:12:52 1969), d: 0)
ts(f: 13609, t: 772800000 (Wed Dec 31 19:12:52 1969), d: 0)
ts(f: 13613, t: 773000000 (Wed Dec 31 19:12:53 1969), d: 0)
ts(f: 13617, t: 773233333 (Wed Dec 31 19:12:53 1969), d: 0)
```

### CODE REVIEW

**Comment by mattdawkins** [comment]
Might want to just change the integration target on this to master now that the first downsampler branch has landed

**Comment by linus-sherrill** [comment]
Jenkins test this please

**Comment by neal-siekierski** [comment]
The Windows build appears to be failing for unrelated testing reasons. At least judging by the end of the build log, it appears that the core Sprokit tests aren't being run.

**Comment by dstoup** [comment]
> The Windows build appears to be failing for unrelated testing reasons. At least judging by the end of the build log, it appears that the core Sprokit tests aren't being run.

The sprokit tests never run on Windows. There is an error in the macro that generates those tests. The GTEST tests don't have this problem. The dashboard is configured to NOT fail because of the 'Not Run' tests.

The failure here is caused by a problem finding the log4cplus plugin library. I think Linus may have made a fix to this issue on another PR.

**Review by dstoup — APPROVED** [review]

**Pull request merged**
