### PR TITLE
Allow pipeline includes in python, test

### PR DESCRIPTION
**Pull request by tao558**
Small PR that adds a missing parameter to the `embedded_pipeline::build_pipeline` binding. This new bound parameter allows users to set a directory where other included pipe files should be included. Also added a test.

### CODE REVIEW

**Comment by tao558** [comment]
Jenkins test this please

**Comment by tao558** [comment]
Jenkins test this please

**Comment by tao558** [comment]
Jenkins test this please

**Comment by dstoup** [comment]
Code-wise, I think this is ok. I am wondering if this PR should go into release, since the other python binding work is there and planned for the upcoming minor release. Thoughts?

**Comment by tao558** [comment]
> Code-wise, I think this is ok. I am wondering if this PR should go into release, since the other python binding work is there and planned for the upcoming minor release. Thoughts?

I think that sounds reasonable

**Comment by tao558** [comment]
Jenkins test this please

**Review by dstoup — APPROVED** [review]

**Pull request merged**
