### PR TITLE
Update release notes

### PR DESCRIPTION
**Pull request by mleotta**
In addition to fixing typos, this branch adds a detailed summary of the major changes in this release.  Please read through this and suggest changes.  I'm sure I don't have the full picture.

### CODE REVIEW

**Comment by mleotta** [comment]
@kfieldho, @collinsr, do you have any comment on the accuracy and completeness of what I have written for release notes?

**Comment by collinsr** [comment]
Line 24: 'that allows introspect of these plugins' --> introspection

Otherwise, looks good!

**Comment by collinsr** [comment]
Although there's apparently no contractural requirement (at least on DIVA's part), and arguably redundant to what's in the bulk of the release notes, I think it would be fitting to add an "acknowledgements" section where we explicitly call out that much of this release was funded by DIVA (and the other projects.)

**Comment by mleotta** [comment]
@collinsr Do you think this should be acknowledgements in the release notes, or an acknowledgements section in the readme?  For example MAP-Tk has such an acknowledgements section in the readme: https://github.com/kitware/maptk#acknowledgements.  I probably should copy a similar AFLR acknowledgement to KWIVER as well since much of the MAP-Tk code has moved into KWIVER.  We could add IARPA, NOAA, and others here as well.

**Comment by collinsr** [comment]
Ah-- I think the acknowledgements section is fine.

**Comment by mleotta** [comment]
I'm going to merge this and we can revise further, if needed, on another branch.

**Pull request merged**
