### PR TITLE
Convert sprokit tools to applet format

### PR DESCRIPTION
**Pull request by linus-sherrill**
Convert the three sprokit tools to the kwiver applet architecture. Tools do not now compete in the global command namespace and are discoverable due to the plugin approach.

### CODE REVIEW

**Comment by dstoup** [comment]
I am seeing the same build error on this clang dashboard. I will double check the machine against master just to see if there is an endemic problem. There are 3 more clang builds staged up for this branch, I am going to kill the oldest 2 to free up cycles.

**Comment by dstoup** [comment]
It looks like an issue with this branch on this CentOS 7 machine (titan, which is on the domain). It doesn't seem to happen on the other CentOS 7 build though. I don't yet know if it's a difference of configuration of something about the systems. I will investigate that further.

**Comment by dstoup** [comment]
Jenkins test this please

**Comment by dstoup** [comment]
The CentOS build is failing because of the Qt5 update.

**Comment by linus-sherrill** [comment]
Jenkins test this please

**Comment by linus-sherrill** [comment]
Jenkins, test this please

**Comment by linus-sherrill** [comment]
Jenkins, test this please

**Comment by dstoup** [comment]
Just took a quick look at the failing Windows tests. Those are the ones that previously failed on the others. They usually run and pass.

**Comment by dstoup** [comment]
It looks like we're finally getting somewhere!

As long as others are fine with the changes (which I think we've already covered), I would say merge!

**Pull request merged**
