### PR TITLE
Add python major version to kwiver-config.cmake

### PR DESCRIPTION
**Pull request by linus-sherrill**
Add KWIVER_PYTHON_MAJOR_VERSION to the kwiver-config.cmake file. This fix addresses issue #583 for interfacing with the kwiver build and install products.

### CODE REVIEW

**Comment by dstoup** [comment]
The change looks great. Is major version sufficient or will we need minor version at some point? Not sure why we would really, major should be enough to use the correct FindPython{2|3} but figured it was worth the ask.

**Comment by linus-sherrill** [comment]
I thought about adding the complete python version, but the issue only mentioned the major version. It can be added. What is the consensus?

**Comment by linus-sherrill** [comment]
I added the full PYTHON version, as it may be useful in the future.

**Comment by mleotta** [comment]
This is sort of a bug fix.  We are preparing an release very soon.  I'm wondering if this change belongs their too.

**Pull request merged**
