### PR TITLE
Perform Imports Alphabetically

### PR DESCRIPTION
**Pull request by mattdawkins**
This makes the log prettier.

But the real reason is this fixes an obscure tensorflow->opencv->pytorch import error when dealing with builds on all of the above, but only on some OS.

### CODE REVIEW

**Comment by linus-sherrill** [comment]
Why does sorting the paths solve the problem?

**Comment by mattdawkins** [comment]
It changes the order of 'imports' as called by the python code. Fairly confident it's a conflict between dependencies tensorflow's build with and other libraries but won't have much time to look into for another month

**Comment by mattdawkins** [comment]
Ameya found this:

https://github.com/tensorflow/tensorflow/issues/19010#issuecomment-386846086

so technically this is a bug in my old Ubuntu OS and this is the only fix; considering it doesn't hurt anything else I'd say it's still worth putting in this fix

**Comment by as6520** [comment]
https://github.com/tensorflow/tensorflow/issues/19010#issuecomment-386846086 sheds some light on the problem but the import order is a mystery.

**Comment by mattdawkins** [comment]
Ameya found this:

https://github.com/tensorflow/tensorflow/issues/19010#issuecomment-386846086

So it is an actual issue - don't think there's a better fix then this

**Comment by linus-sherrill** [comment]
This is not a very robust solution to a dependency ordering problem. What if a file gets renamed? Generating a dependency graph would be a provably correct solution.

**Comment by mattdawkins** [comment]
A dependency graph would require more complicated code for an issue which isn't going to come up often (or if all) again, not to mention having to hard-code or soft-code values in a config file?

**Pull request closed without merging**
