### PR TITLE
Fixed bug with the depth step for ffmpeg reader

### PR DESCRIPTION
**Pull request by chetnieter**
Fixed bug where the depth step for the output images for the ffmpeg
implementation of video_input was not set correctly.

### CODE REVIEW

**Comment by mleotta** [comment]
This change looks good, but I think it probably applies to the `release` branch since this bug should also be in the last release.  Please rebase on `release` and add a release note in the bug fixes section of `release.txt`

**Comment by chetnieter** [comment]
Closing since this should goto release branch

**Comment by chetnieter** [comment]
@mleotta Do copyrights need to be updated here as well?

**Comment by mleotta** [comment]
It couldn't hurt.  It's probably less important for a minimal change like this, but I see no reason not to.

**Pull request closed without merging**
