### PR TITLE
Create video metadata filter

### PR DESCRIPTION
**Pull request by mwoehlke-kitware**
Create an algorithm that wraps a video input and applies a transformation to the metadata. Right now, this is implemented via a pure virtual function, meaning that users need to subclass the algorithm to use it. (This will likely be replaced, later, with a proper algorithm, but for now we don't have such an algorithm yet.)

### CODE REVIEW

**Review by russelldj — APPROVED** [review]
Looks good to me. This is not critical to this PR, but looks like we're planning to have the `transform_metadata` function return a single vector of metadata. I think it's worth discussing in the future how exactly we want to differentiate between raw metadata provided by the file and derived metadata, since my understanding was we wanted to include both in the output.

**Comment by mwoehlke-kitware** [comment]
> looks like we're planning to have the `transform_metadata` function return a single vector of metadata. I think it's worth discussing in the future how exactly we want to differentiate between raw metadata provided by the file and derived metadata, since my understanding was we wanted to include both in the output.

My understanding was that we were just going to prepend additional items to the vector, or some such. Note that we also can't change the API to something radically different because use of this process needs to be transparent to users that don't know about it.

**Comment by mleotta** [comment]
A metadata object contains a `METADATA_ORIGIN` tag, which has a value like "MISB_0601" for data from KLV.  We could add an additional metadata object to the vector after each 0601 object with a different `METADATA_ORIGIN` value.  Maybe something like "KWIVER Derived".  However, this would require a change in some of the downstream users of metadata, like the GUI display and CSV writer.  Those would need to take and combine the first metadata objects that have different origins rather than just take the first one.

**Review by daniel-riehm — APPROVED** [review]
Looks good to me.

**Comment by mleotta** [comment]
The code looks okay, but is this actually usable with `transform_frame_metadata` being pure virtual?  I thought the plan was to hard code this to use the GSD/VNIIRs metadata function for now and then generalize later by creating a new abstract algorithm for `metadata_filter` to use instead.  To use this, for now, we need to derived a class from this, which we would then throw away later when switching to the `metadata_filter`.  I suppose that's okay if we don't mind creating a class and then deleting it later.

**Comment by mwoehlke-kitware** [comment]
> is this actually usable with `transform_frame_metadata` being pure virtual? I thought the plan was to hard code this to use the GSD/VNIIRs metadata function for now

...but does that logic, even in the short term, belong *in `video_input_metadata_filter.cxx`*? (Never mind it "doesn't exist" yet.)

My short-term thinking was that users would subclass `video_input_metadata_filter` and directly implement the filtering (which might be simply calling some other function from KWIVER, i.e. I don't expect that class to be more than *maybe* a dozen lines of code). What we're still punting on for now is wrapping this functionality in an algorithm, which requires making a separate interface class for it, going through the machinery to instantiate the algorithm, etc.

**Comment by mleotta** [comment]
It doesn't seem like it would too difficult to create the abstract `metadata_filter` API in vital, even if there is no implementation for it yet.  That way in the future we just have to implement the missing metadata filter algorithm.  Otherwise we need to derive some `video_input_gsd_metadata_filter` temporarily and give it some name and register that in the plugin.  Then when we change it later we have to delete that temporary class and switch back to `video_input_metadata_filter`, which is a larger API change.

I was originally thinking we would just hard code `video_input_metadata_filter` to be `video_input_gsd_metadata_filter` temporarily, which is not ideal either.  Given the desire to keep `video_input_metadata_filter` generic from the start, I suggest we just make the `metadata_filter` API and use it.

**Pull request merged**
