### PR TITLE
Add mechanism to obtain a description of a CRS

### PR DESCRIPTION
**Pull request by mwoehlke-kitware**
Add a new geodesy function that takes a CRS and returns a map of key/value pairs that describe various well-known properties of the CRS.

### CODE REVIEW

**Comment by mleotta** [comment]
Looks reasonable, but it would be nice to see a unit test for this (in arrows/proj/test), mostly for coverage sake.  It could be something simple that calls this function for one or two common CRS values and validates the output against the expected value.

Otherwise the code looks good.  I might merge in master just to get Travis CI run properly on this branch and remove that red x.

**Comment by linus-sherrill** [comment]
Jenkins test this please

**Comment by mwoehlke-kitware** [comment]
> it would be nice to see a unit test for this

I expanded the `vital:geodesy` test. This will test whatever geodesy conversion functor is registered. (Note that this is not the first test in `vital/types` to assume a functor is registered; the `vital:geo_point.conversion` and `vital:geo_polygon.conversion` test cases already do likewise.)

**Comment by mwoehlke-kitware** [comment]
One hitch: this uses `<regex>`, which [requires GCC ≥ 4.9](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=53631)...

**Pull request merged**
