### PR TITLE
Dev/replace boost::variant

### PR DESCRIPTION
**Pull request by linus-sherrill**
Replace boost::variant with an implementation which is compatible with the new std:: version that will be available in c++17. The std:: version can be substituted with minor changes to the code.

The variant implementation has been shamelessly borrowed from github and bashed to fit. Mostly by changing the name spaces to be compatible with the code base.

### CODE REVIEW

**Comment by linus-sherrill** [comment]
Jenkins test this please

**Comment by dstoup** [comment]
Jenkins test this please

**Comment by linus-sherrill** [comment]
Jenkins test this please

**Comment by dstoup** [comment]
Looks like there is a valid Window error in this iteration.

**Comment by linus-sherrill** [comment]
Jenkins test this please

**Pull request merged**
