### PR TITLE
Dev/reduce warnings

### PR DESCRIPTION
**Pull request by linus-sherrill**
Remediate some warnings when using KWIVER_CPP_EXTRA option.
    
    Specifically:
    - addressing unused parameters
    - shadowed variables
    - old style casts
    - adding default case to switch statements

### CODE REVIEW

**Comment by mwoehlke-kitware** [comment]
This is a LOT of churn. Any chance you could split out the changes for unused parameters from everything else, for easier review?

**Comment by mwoehlke-kitware** [comment]
Incidentally, I'm pretty sure the reason `-Wshadow` wasn't on by default is precisely *because* there are some utterly asinine names in the global namespace due to the C standard library that are never used as such, but are frequently wanted for local names (`id`, `index`), and as such I tend to look at that warning as overly pedantic. (Also, because shadowing generally isn't harmful.)

**Comment by linus-sherrill** [comment]
That being said, I found  some bugs that were obscured by allowing shadowing.

**Comment by mwoehlke-kitware** [comment]
I wonder if `-Wshadow=local` would be adequate? *That* one makes (much more) sense being on by default. (Though I think it would be obnoxious for e.g. SEAL-TK).

**Comment by linus-sherrill** [comment]
@mleotta - There is a comment marker in arrows/mvg/algo/initialize_cameras_landmarks.cxx:1068 where a local variable shadows a member variable. The variable uses the `m_` idiom, so I am not sure if the intent was to use a local variable or to set the member variable.

**Comment by linus-sherrill** [comment]
I'll take care of that.

**Comment by linus-sherrill** [comment]
This MR has been broken into several smaller more topical MR's

**Comment by mwoehlke-kitware** [comment]
> This MR has been broken into several smaller more topical MR's

Thank you!

FTR: #1113, #1114, #1115 and #1116.

**Pull request closed without merging**
