### PR TITLE
Adding test for render-mesh command

### PR DESCRIPTION
**Pull request by OwenMcGee**
Currently the command seems to hang on the "reading mesh" step, even with proper input.

Also, providing a config file input seems to result in an error: `std::bad_cast`

### CODE REVIEW

**Comment by mleotta** [comment]
@OwenMcGee I'm not sure what these kwrobot-v1 errors are all about, but maybe it's related to Windows line endings again.  Can you try converting the ASCII PLY file to use unix line endings and see if that makes a difference?

**Comment by mleotta** [comment]
jenkins please test this

**Comment by mleotta** [comment]
jenkins please test this

**Comment by OwenMcGee** [comment]
@mleotta the file endings were already fine, and I believe you're using the command wrong (it should be "jenkins test this please")

**Comment by mleotta** [comment]
Ah, I can never remember which way it is.

**Comment by mleotta** [comment]
jenkins test this please

**Pull request merged**
