### PR TITLE
_USE_MATH_DEFINES needs to come first so we have a definition of M_PI…

### PR DESCRIPTION
**Pull request by dstoup**
_USE_MATH_DEFINES needs to come first so we have a definition of M_PI on Windows

### CODE REVIEW

**Comment by mleotta** [comment]
My preference would be to avoid using these non-standard definitions like `M_PI` altogether.  They may have slightly different definitions (e.g. different levels of precision) across platforms/compilers.  There are no standard definitions of numerical constants, like pi, in C++.   It would be better to just define some `constexpr` values for use in KWIVER.  Maybe we need a math_constants.h in vital.

**Comment by dstoup** [comment]
@mleotta do you propose we do that as part of this branch, or can we merge this one to get Windows building and replace those constants in a follow-up branch?

**Comment by mleotta** [comment]
It's fine to do it in a separate branch.  I understand the need to get the dashboards green first.

**Comment by dstoup** [comment]
Jenkins test this please

**Pull request merged**
