### PR TITLE
[WIP] Fixed broken CSV detection reader (#516)

### PR DESCRIPTION
**Pull request by linus-sherrill**
This PR is a second pass at modifying the detected object reader, CSV format.

* Improved the process of extracting detections per frame
* improved commenting and naming
* Only create map when needed. Should address CI issues
* Only create map when needed. Should address conflicts
* Tidied up from the last commit
* Reverted last three commits and hopefully fixed CI errors
* Changed the logger
* Changed to the correct logger

### CODE REVIEW

**Comment by linus-sherrill** [comment]
These changes introduce a semantic change in the abstract
class. Specifically the read_set() method. Originally the `image_name`
was an output parameter. This change to the CVS format reader makes it
an input/output parameter with special handling if the string is
empty. This semantic change would need to be propagated to all other
implementations of this reader. Currently only the CSV reader works
this way.

**Comment by dstoup** [comment]
The core:detected_object_io.stream_io test still fails on Linux

**Comment by dstoup** [comment]
... aside from the Windows build failures.

**Comment by mattdawkins** [comment]
FYI we have already propogated this change to the same CSV readers in VIAME (habcam and noaa csv)

**Pull request closed without merging**
