### PR TITLE
Use old initializer for stringstreams

### PR DESCRIPTION
**Pull request by tao558**

### CODE REVIEW

**Comment by tao558** [comment]
Jenkins test this please

**Comment by dstoup** [comment]
Jenkins test this please

**Comment by dstoup** [comment]
I think we need to add you to the whitelist, Tom, so you can trigger the dashboard runs.

**Comment by tao558** [comment]
> I think we need to add you to the whitelist, Tom, so you can trigger the dashboard runs.

Thanks, sorry for the delay.

**Comment by dstoup** [comment]
Mac finished but just looks hung. Merging. Thanks all!

**Pull request merged**
