### PR TITLE
Fixup SKBUILD linking order and RPATH

### PR DESCRIPTION
**Pull request by johnwparent**
Reorders FFMPEG dependency linking, fixes CMake bug when SKBUILD flag is set, when SKBUILD is set, adds install location of wheel libs to RPATH of libs built with `kwiver_add_library` 

Changes made to facilitate production of Kwiver python wheels.

### CODE REVIEW

**Review by dstoup — COMMENTED** [review]
Looks good to me.

**Comment by johnwparent** [comment]
Glad to hear it, while I'm here, do you think it's worth reordering the remainder of the FFmpeg dependencies, or are we ready to merge and move on?

**Comment by dstoup** [comment]
Looks like I was supposed to comment, sorry for the delay. I don't think we *need to do anything more but if it makes sense to reorder FFmpeg deps and it doesn't cause undo harm, then I would say yes. Otherwise, we can merge and move on.

**Comment by johnwparent** [comment]
Ok, in that case, I'll give them a quick reorder as per the FFmpeg FAQ and then we can go from there.

**Pull request closed without merging**
