### PR TITLE
OpenCV code updates

### PR DESCRIPTION
**Pull request by mleotta**
`arrows/ocv` does not require OpenCV highgui, so don't use those includes.  Way back in OpenCV 2.4 it used to be the case that you needed highgui for image IO, but this hasn't been true since v3.0.

Also, the examples still used `cvDestroyWindow`, which is a v2.4 function that was deprecated in v3.X and removed in v4.X.  Switching to `cv::destroyWindow` should work for v3.X or v4.X.

### CODE REVIEW

**Comment by mwoehlke-kitware** [comment]
I take it from your description that this won't work for OpenCV 2.4? We still have logic to support that; should it be removed? Should we also change our CMake logic to require at least 3.x?

**Comment by mleotta** [comment]
I actually don't know for sure if it will work with OpenCV 2.4, but I expect not.  We have officially removed OpenCV 2.4 from Fletch, so I think it's safe to say that we are no longer supporting it.  We probably should require at least 3.X in KWIVER CMake.  At some point we could also clean up the logic that is scattered around that supports 2.4, but that's lower priority.

**Comment by dstoup** [comment]
Agreed! OpenCV v2 is long gone.

**Review by dstoup — APPROVED** [review]

**Comment by mleotta** [comment]
I've updated KWIVER CMake to require OpenCV >= 3.0.  That should be sufficient for now.  We can clean up to remove special handling for OpenCV 2.4 in a future branch.  It's not hurting anything to leave that in for now, it would just be nice to clean up at some point.

**Comment by mleotta** [comment]
@mwoehlke-kitware With CMake logic updated to require at least OpenCV 3.0, is this good enough to merge?  My focus here is full compatibility with OpenCV 4.  We can do more cleanup of old OpenCV 2 code later.

**Pull request merged**
