### PR TITLE
Implement camera resection

### PR DESCRIPTION
**Pull request by mwoehlke-kitware**
Create an OpenCV-based implementation of the `resection_camera` algorithm.

### CODE REVIEW

**Comment by mwoehlke-kitware** [comment]
@borovik135, you should probably check I didn't break anything when renaming variables 🙂. 
2a2a3fa (the first commit) should be content-identical to your #1269, though.

**Comment by mwoehlke-kitware** [comment]
> which remote should I set to check out this particular commit to check if anything is broken due to variable refactoring?

If you check the top of the PR page, there is a link to [mwoehlke-kitware/kwiver:dev/resection-camera](https://github.com/mwoehlke-kitware/kwiver/tree/dev/resection-camera), which will lead you to `git://github.com/mwoehlke-kitware/kwiver`.

**Comment by mwoehlke-kitware** [comment]
...ack, and it looks like I broke the Python bindings (probably from fiddling with the API). I can't look now, and, um, actually do those even work properly for output parameters?

**Comment by mleotta** [comment]
The failing test seems completely unrelated to this branch

**Comment by mleotta** [comment]
Jenkins test this please

**Comment by mleotta** [comment]
`test-core-dynamic_configuration` is consistently failing due to time out on this branch but not on other KWIVER branches.  It's not obvious to me what that test has to do with the changes on this branch.

**Comment by mleotta** [comment]
@mwoehlke-kitware Can you dig into the logs of the Windows CI failure and figure out what is going wrong here?  I ran CI twice with the same outcome and CI is passing on other branches.  I'd like to get this merged.

**Comment by dstoup** [comment]
I've seen two other tests regularly fail on Windows CI because of this timeout issue, but never this test. Also, I usually only see these failures during the 'build kwiver' portion of a Fletch PR.

**Comment by mleotta** [comment]
Let me run CI one more time.  I can't see how this timeout is related to changes on this branch, but the failure did happen in two runs of the CI and doesn't appear to be happening on other branches.

**Comment by mleotta** [comment]
Jenkins test this please

**Comment by mwoehlke-kitware** [comment]
```
  CMake Error at C:/Program Files/CMake/share/cmake-3.17/Modules/GoogleTestAddTests.cmake:40 (message):
    Error running test executable.
  
      Path: 'C:/workspace/KwiverWindowsPR/build/bin/Release/test-core-dynamic_configuration.exe'
      Result: Process terminated due to timeout
```
Ack... that's completely unhelpful without being able to try to run the test, possibly in-situ, in a more controlled environment. Also, it *does* seem to happen randomly for no apparent reason. It's a little surprising it would affect the *same* test more than once, though.

**Comment by dstoup** [comment]
> ```
>   CMake Error at C:/Program Files/CMake/share/cmake-3.17/Modules/GoogleTestAddTests.cmake:40 (message):
>     Error running test executable.
>   
>       Path: 'C:/workspace/KwiverWindowsPR/build/bin/Release/test-core-dynamic_configuration.exe'
>       Result: Process terminated due to timeout
> ```
> 
> Ack... that's completely unhelpful without being able to try to run the test, possibly in-situ, in a more controlled environment. Also, it _does_ seem to happen randomly for no apparent reason. It's a little surprising it would affect the _same_ test more than once, though.

The characteristics of this behaviour that I've always seen ... it's always the same tests and I've never been able to reproduce it outside of the dashboard. Also, once I see the failure, it almost always fails. No idea what is causing it. I've tried a number of different times with a few different approaches and never gotten anywhere with it. I've also looked but never noticed anything fundamentally different about the tests themselves that might contribute to the issue.

**Review by mleotta — APPROVED** [review]

**Comment by mleotta** [comment]
It looks like that Windows failure was a fluke after all.

**Pull request merged**
