### PR TITLE
Add initial track IO readers/writers, and a few simple tracking framework processes

### PR DESCRIPTION
**Pull request by mattdawkins**

### CODE REVIEW

**Comment by mattdawkins** [comment]
I guess I should remove all VITAL_FOREACH's and resolve conflicts as a first step

**Comment by mleotta** [comment]
I've asked @mattdawkins to break this PR down further into smaller PRs.  At least into the three different topics that are in the title.  This is too big for a review

**Comment by mattdawkins** [comment]
I've updated it for the latest master. If it's fast I'll break it down into 2 branches, but am not going to spend much time on it since all of these changes need to land regardless.

**Comment by hughed2** [comment]
Jenkins test this please

**Comment by hughed2** [comment]
Jenkins test this please

**Comment by hughed2** [comment]
Jenkins test this please

**Comment by mattdawkins** [comment]
I added some release notes to the branch, in the interests of time and because there are several other branches after this I'm proceeding with merging this unless people comment on its contents.

**Comment by dstoup** [comment]
Jenkins test this please

**Comment by dstoup** [comment]
I disagree with going ahead and merging. Matt Leotta is correct, this is too much code for a PR. You should split it up into smaller functionally relevant pieces and consider NOT building huge forks in the future.

**Comment by mattdawkins** [comment]
Disagreement noted - And I agree with you as well, in an ideal world.

**Comment by mattdawkins** [comment]
Jenkins test this please

**Pull request merged**
