### PR TITLE
Fixed error in doxygen file name

### PR DESCRIPTION
**Pull request by mleotta**

### CODE REVIEW

**Comment by mleotta** [comment]
@borovik135 This is what I meant about applying this bug fix change as a separate PR for the release branch.

**Review by borovik135 — APPROVED** [review]
I have recently learned that doxygen allows to leave the \file operand blank, in which case the containing file name is supplied during doxy compilation.

**Comment by borovik135** [comment]
thanks for taking care of this, it looks good to me, tnx!

**Comment by mleotta** [comment]
@dstoup @Cookt2 Is the Window CI machine down.  We have a number of branches that are waiting on results from the Windows build.

**Comment by mleotta** [comment]
This only changes doxygen strings so I don't think I need to rerun the CI.  Merging.

**Pull request merged**
