### PR TITLE
Update to PROJ 5

### PR DESCRIPTION
**Pull request by mwoehlke-kitware**
Overhaul the PROJ arrow to use the PROJ 5 API. We need to do this eventually as the PROJ 4 API is deprecated and must be opted into for PROJ 6.x, and is removed entirely by PROJ 8.x.

Obviously, this requires PROJ ≥ 5.0. The updates to the find module should fail to find PROJ < 5. Superbuilds will also require Kitware/fletch#651 (which has been merged).

### CODE REVIEW

**Comment by dstoup** [comment]
I think the code itself looks good and seems to jive with my minimal understanding of what needed to be done to support the new API. I'm inclined to approve once CI is working.

**Comment by dstoup** [comment]
Jenkins test this please

**Comment by mwoehlke-kitware** [comment]
Sigh... what a roller coaster. The previous version of this PR worked with PROJ 6 (which is what I have locally), but had quite a few issues with PROJ 5. It seems there were several breaking changes to the "new" API between 5 and 6. I *think* this should now be working with both.

**Comment by mwoehlke-kitware** [comment]
Jenkins test this please

**Comment by mwoehlke-kitware** [comment]
Abandoned: the new plan is to jump to PROJ 6 and not support PROJ 5. An updated and rebased version of this PR will be pushed once fletch adds PROJ 6.

**Pull request closed without merging**
