### PR TITLE
Remove virtual keyword from feature.get_color

### PR DESCRIPTION
**Pull request by tao558**
This PR makes a small change to the kwiver vital type "feature". feature.get_color() was marked as virtual unnecessarily, which is fixed in this PR. 

This PR also removes the unnecessary "virtual" specifier on inherited methods and adds the override specifier

### CODE REVIEW

**Comment by tao558** [comment]
Jenkins test this please

**Comment by linus-sherrill** [comment]
Jenkins test this please

**Comment by mleotta** [comment]
This looks good to me.

**Comment by tao558** [comment]
@linus-sherrill asked me to include an additional change to the file, which was just pushed.

**Comment by linus-sherrill** [comment]
Jenkins test this please

**Pull request merged**
