### PR TITLE
Aggressively prevent reparenting track states

### PR DESCRIPTION
**Pull request by mwoehlke-kitware**
Track states differ from most objects in that they back-reference their owning track. Accordingly, we prevent them from being added to a track if they already have an owning track. However, users may not be aware of this caveat (and indeed, multiple instances of this form of misuse have been recently uncovered), and may not be checking for failures to add track states to a track, since the "obvious" failure cases can often be statically known to not occur.

In order to help address these issues, modify the code which adds track states to make it a logic error (i.e. literally throw `std::logic_error`) when attempting to add an already-owned track state to a track, as this almost always indicates that the code attempting to perform the operation does, in fact, contain a logic error. This should make it much easier to identify such code, rather than having to chase down more subtle bugs due to track states unexpectedly "going missing".

### CODE REVIEW

**Comment by mwoehlke-kitware** [comment]
@mleotta, for now I have left the return value for the "key problem" failure modes. Those aren't causing known bugs, and I'm not 100% convinced they should be exceptions. More, however, making that change is going to require touching quite a bit of existing code, much of which "isn't mine", so at least I think it should be done as a separate PR. This minimal change is needed to identify and squash the known issues.

**Comment by mattdawkins** [comment]
At a glance I think that not allowing sharing track states between multiple tracks is a bad idea for efficiency reasons, and creates un-neccesary copying in my use case (the track gets 1 state bigger at at time but all the states up to that state remain unchanged). At a minimum, I know that object detections within track states cannot be deep copied within my application. I'll check in people about this over the day or two work days to see if it can be avoided.

**Comment by mleotta** [comment]
I did not review these changes yet, but want to respond to @mattdawkins concerns.  The current track data structures were carefully designed a few years ago to make indexing into tracks very fast, whether indexing by track id or by frame number, while also supporting track manipulation like extending and merging tracks. To make this work, the each `track_state` needs to have a weak pointer back to it's unique parent track.  `track_state`s cannot share parents.  A `track_state` also needs to be a light weight object that is efficiently copied.  That said, there is no problem with multiple `track_state` objects sharing a pointer to a common payload object which may be heavy (as long as the shared payload is treated as const).   The track states are typically shallow copied when copying tracks.  A `track_state` should be nothing more than a frame id, and weak pointer to a parent track, and payload.  The payload should be one or more light weight objects or shared pointers to heavier objects.

I believe I played around a bit with having the `track_state_payload` be an explicit class and the `track_state` be an implementation details that ties things together, but this design was a lot more clunky and didn't align with the patterns ported over from vidtk.  It's better the way it is now, but you do have to be aware that `track_state`s need be cloned when reusing them between tracks, and `track_state`s should be light wrappers around payload data for this reason.

**Comment by mattdawkins** [comment]
But the track_states now have other variables in them. Particularly the object_track_state. While likely negligible, this will still make the code slower, and all python trackers (with the current bindings) more complicated, with absolutely no benefit to any object tracker code we currently have.

**Comment by mleotta** [comment]
@mattdawkins I highly doubt this is a bottleneck in your code.  You don't have that much stored in the `object_track_state`.  However, if you profile the code and find that copying does make big difference, then the appropriate fix would be to switch your `object_track_state` to use a PIMPL model internally.  Put all of your data in a single payload object with a shared pointer and then shallow copy that pointer when copying track states.

**Comment by mattdawkins** [comment]
Excessive pointer copies makes code look ugly with nested pointers, though we have this with some of the heavy stuff in the detection object which is what I'm not copying no matter what (pixel-level masks).  Even though it's not a bottleneck, there's the question of why would we do something with no benefit and is slower? Maybe append should have a boolean for this check, in your case it can be defaulted to on so it doesn't affect your code.

Maybe object tracks and feature tracks should not have had have a shared hierarchy in the first place, since for object tracks we often like indexing by time instead of frame ID.

**Comment by mwoehlke-kitware** [comment]
> I think that not allowing sharing track states [...]

I just want to point out that this is *already* not permitted. Right now, if you try it, the call to `append`/`insert` just fails (returns `false`), which has caused bugs where tracks are unexpectedly missing states. All this PR does is promote the failure to something much more obvious.

> However, it occurs to me that there is another way that may be more friendly to novice users. Rather than return `bool` these functions could return the `track_state_sptr` that was actually merged

That's another possibility, although I think it may force an extra reference counting operations that is unnecessary in some instances. I also worry a little whether users will pay attention to the return value. Yes, the current approach isn't as "friendly" as it could be, but I think it is the *safest*. (Anyway, I expect it is nearly always statically known if users are trying to add a state that is already owned or not, and if I'm wrong, we can always add an `is_orphan` or the like.)

That said, I think I would like to investigate making these functions take r-values, with overloads taking copies (which can just `std::move` their argument and trampoline to the r-value versions). This should make it possible to save a reference counting operation in the case that a freshly-made clone is passed in.

> or maybe return the updated `track_state_sptr` by reference and also return `bool`

Besides that I ***loathe*** output parameters, I don't think there is any benefit. I don't think this would actually save a reference count, and the return value is always exactly `!!out_ptr`, so there is no added value in separating them. (Also, I would be worried that a) potentially modifying the input argument adds another subtle trap, which is exactly what we're trying to *eliminate*, and b) there would be existing users trying to pass an immutable pointer that now need to perform extra gyrations just to call the function. OTOH, the latter are probably all instances of *mis*use...)

**Comment by mleotta** [comment]
The current design has been shown to have enormous benefits when the number of tracks gets large.  So I think this would be very beneficial for object tracks in applications like WAMI tracking where there are many object tracks.  It probably does not have any benefit when the number of is small.  Then again, the cost of copying tracks is also minimal if the number of tracks is small.

I still think it makes sense to use a common code base for both types of tracks.  All the optimization we did for large feature tracks set will pay off for large sets of object tracks.  However, if you can demonstrate that these small copies are significantly hurting your performance then we should revisit.  But we should not speculate and optimize things that don't really need to be optimized.

**Comment by mattdawkins** [comment]
My concern is exactly when the tracks get large, since now on the python side we will be copying 100,000 state objects every iteration (frame) per track. Maybe in your implementation you're only sending incremental updates as opposed to the entire track downstream but we don't have bindings for reconstructing those objects on the python side, and I don't want to support sending incremental updates yet due to lack of time and these feedback loops we have between 4 sprokit processes. Regardless of what happens in master, in viame/master I will be removing these checks for short-term work at a minimum if they land.

I guess I was alluding more to having instead of one 'track.h' an 'feature_track.h', 'object_track.h'; right now to get around some of these issues, they could still be derived from the same track.h. Right now we just have object_tracks at the _set and _state levels.

**Comment by mleotta** [comment]
We should take this discussion off line.  I think there is a lot more to unpack and debate here about the design of tracks.  This branch is not the place for that.

**Comment by mattdawkins** [comment]
I think the better solution is probably a more track-view like object wrapping a base track object which expands over time but is still the same object, but can talk about it more on Monday or Tuesday in person.

**Comment by linus-sherrill** [comment]
Jenkins, test this please

**Comment by mleotta** [comment]
@mattdawkins the code has required a shallow copy of track states for several years now.  It just returned false and didn't complain loudly if you didn't do it, and that has led to subtle errors.  This branch doesn't change how it works, it just makes it more obvious (by throwing an exception) when you try to incorrectly reuse a track state without making a copy.  It will help track down current errors in tracking code.

I'd recommend that we merge this and then discuss possible track_state design changes if still needed.

**Comment by linus-sherrill** [comment]
I will merge this tomorrow unless I hear otherwise.

**Comment by mattdawkins** [comment]
Merge it if you want, I'm just afraid if I don't push the point it won't happen. On viame/master I've already reverted it but in the future I'll try to come up with a PR which I think better addresses this or tries to address both of our cases.

**Pull request merged**
