### PR TITLE
Add image file name support for VXL image reader

### PR DESCRIPTION
**Pull request by linus-sherrill**
Added code to put image file name into the metadata structure that goes with the image_container. This support had been added to the OCV variant but not to the VXL variant.

Also changed the name of metadata tag for image_filename and video_filename to be IMAGE_URI and VIDEO_URI. This better describes what the contents could be.

### CODE REVIEW

**Comment by linus-sherrill** [comment]
Jenkins, test this please

**Comment by dstoup** [comment]
Jenkins, test this please

**Comment by dstoup** [comment]
Looks great once dashboards are happy.

**Comment by dstoup** [comment]
Jenkins test this please

**Pull request merged**
