### PR TITLE
Fix a bug typo in a cmake file that was missing a closing bracket

### PR DESCRIPTION
**Pull request by Purg**
This came up as an issue trying to locally build the python wheel.

### CODE REVIEW

**Review by mleotta — CHANGES_REQUESTED** [review]
this is a bug fix and should probably target the release branch instead.

**Comment by Purg** [comment]
Valid. I will get to rebasing and changing release note target after a meeting.

**Comment by Purg** [comment]
So it looks like this fix is on the release branch but it is not on master. What's correct thing to do here?

**Comment by mleotta** [comment]
If that's true then something went wrong in our process.  Whenever a branch
lands in release we are supposed to merge release into master (it would be
nice to automate that in the future if we can, or at least test in CI if
release is not reachable by from master in Git history)

It sounds like we need to merge release into master to get back to a valid
state.

**Comment by Purg** [comment]
Strike that, I made a rookie mistake of not updating my local release branch checkout. I can see the bug actually on release. Let me fixup and get a force update.

**Review by johnwparent — APPROVED** [review]

**Comment by Purg** [comment]
Checking back in. This is now based on release and has a positive review from @johnwparent. What's the next action here / who's responsible for merging?

**Review by mleotta — APPROVED** [review]

**Pull request merged**
