### PR TITLE
bundle adjustment applet

### PR DESCRIPTION
**Pull request by borovik135**
This bundle adjustment applet has been reviewed and approved for public release by DARPA as DISTAR case 36967. It appears to build and run based on current master. Now it needs a review before merging into the master branch.

### CODE REVIEW

**Comment by borovik135** [comment]
@Purg , can we land this? You reviewed and blessed it before the public release request. Now that it was approved by the gvmt, we need to land it in the kwiver master.

**Comment by Purg** [comment]
> @Purg , can we land this? You reviewed and blessed it before the public release request. Now that it was approved by the gvmt, we need to land it in the kwiver master.

This fell off my radar.

@mleotta As someone more knowledgeable in this area, I wanted to get your blessing before clicking any large green buttons.

@daniel-riehm David pointed towards you about kwiver CI things. I don't see under the checks here that any CI was run, and I believe at one point there was CI, so I wanted to check in with you on what needs to happen, if anything, for CI checks to be run.

**Comment by daniel-riehm** [comment]
jenkins test this please

**Comment by Purg** [comment]
@daniel-riehm Thanks!

**Comment by borovik135** [comment]
Windows build has been pending for more than a day now, and that seems to be holding the whole landing process. I wonder if there is a way to persuade that win build to complete any time soon.

**Comment by daniel-riehm** [comment]
Looks like the Windows machine got rebooted or something without restoring the CI runner. It should start working through the backlog now.

**Comment by borovik135** [comment]
Windows build is reported to fail with a bunch of unit tests not built/run, which are not related to this PR. Is there a way to make sure the win build builds/runs tests as other systems do?

**Review by Purg — APPROVED** [review]

**Comment by daniel-riehm** [comment]
The tests fail because compilation fails:

```
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\memory(3089,1): error C2027: use of undefined type 'kwiver::arrows::mvg::bundle_adjust_tool::priv' (compiling source file D:\workspace\KwiverWindowsPR\arrows\mvg\applets\register_applets.cxx)
```

**Comment by Purg** [comment]
I was also reminded that we should add something to the release notes, I assume targeting the `doc/release-notes/master.txt` file.

**Comment by daniel-riehm** [comment]
Failure may because `priv` is declared as a `class` but defined as a `struct`? Don't know for sure, but that's the first thing that pops out.

**Comment by borovik135** [comment]
jenkins test this please

**Review by Purg — APPROVED** [review]

**Pull request merged**
