### PR TITLE
WIP: Removing viscl arrow

### PR DESCRIPTION
**Pull request by chetnieter**
Removing the experimental viscl arrow. The VisCL library is no longer maintained.

### CODE REVIEW

**Comment by chetnieter** [comment]
@mleotta PTAL

**Comment by chetnieter** [comment]
Jenkins test this please

**Comment by chetnieter** [comment]
Mark as Work in Progress since VisCL arrow needs to be removed from documentation as well.

**Comment by linus-sherrill** [comment]
The conflicts need to be resolved.

**Comment by chetnieter** [comment]
This is related to #1581. Rather than reopen this MR a new one should be opened.

**Pull request closed without merging**
