### PR TITLE
Back ports from the master branch

### PR DESCRIPTION
**Pull request by mleotta**
This PR contains a back port (squashed and cleaned up to remove extraneous commits) of #1310 and #1345 so we can include them in the release.  This is a subset of code that was previously reviewed and approved for `master`.  If the CI passes it should be good to merge.

### CODE REVIEW

**Comment by mleotta** [comment]
Jenkins test this please

**Comment by mleotta** [comment]
@borovik135 I've rebased to the `release` branch and squashed your recent changes that we can include them in the pending release of KWIVER.  Please spot check and make sure I didn't mess anything up.  This PR contains reviewed code and should not need another full review.  It's all already in master.

**Comment by mleotta** [comment]
@dstoup is something up with the CentOS build?

**Comment by dstoup** [comment]
Jenkins test this please

**Comment by dstoup** [comment]
Centos build is all set.

**Pull request merged**
