### PR TITLE
Dev/deboostify track oracle

### PR DESCRIPTION
**Pull request by collinsr**
Remove Boost dependencies from the active parts of track_oracle.

There are references to boost's time/date utilities in the 4676 and APIX formats, but these are disabled for other reasons.

### CODE REVIEW

**Comment by collinsr** [comment]
(Just observing that as of 3b82c03 the branch is actually **building** on Travis.)

**Comment by dstoup** [comment]
Jenkins test this please

**Comment by dstoup** [comment]
LGTM, Any objections?

**Comment by linus-sherrill** [comment]
LGTM

**Pull request merged**
