### PR TITLE
Update documentation style in track.h

### PR DESCRIPTION
**Pull request by mwoehlke-kitware**
# ***REQUEST FOR COMMENT***

This is an ***RFC*** for creating and starting to apply a "blessed" style for documentation. The actual style is still under discussion; this PR is being submitted primarily for the purpose of continuing that discussion and, as was suggested, providing an example of the proposed style.

## Proposal

<dl>
<dt>Use <code>///</code> for all doxygen documentation.</dt>
<dd>This is slightly easier to type, slightly more terse (no trailing <code>*/</code> line), and, due to each line starting in the same column with the same sequence of characters, somewhat less prone to formatting butchering by editors. There is also no question of whether to start text on the same line as <code>/**</code> (visually inconsistent) or not (another "unneeded" line).</dd>
<dt>End all documentation with a period, including brief documentation consisting of a single sentence.</dt>
<dd>This is fairly common practice, and improves consistency by ensuring that all documentation renders as terminated sentences, both in the generated HTML and in the corresponding source. (Note that this is specific to <em>documentation</em>; regular comments may use a different policy.)
<dt>Use <code>\command</code> rather than <code>@command</code>.</dt>
<dd>This style is more prevalent, both in KWIVER's extant documentation and withing Doxygen's own documentation.</dd>
<dt>Use a single space after sentences.</dt>
<dd>Not counting copyright banners (which use a single space), we are about evenly split in this respect. A single space, however, is much easier to tool-enforce, as it is difficult to programmatically determine when a double space is appropriate.</dd>
<dt>Omit superfluous documentation.</dt>
<dd>Documenting a copy constructor as "copy constructor" is essentially a waste of space. Just as excessive use of code comments to state the obvious is discouraged, we should also avoid documentation that is effectively gratuitous.</dd>
<dt>Avoid "wordy" starts to brief documentation.</dt>
<dd>While open for discussion, starting brief descriptions with unnecessary articles ("a", "the", etc.) is unnecessary and makes the brief descriptions feel unnecessarily "wordy". (Note that this does *not* apply to detailed descriptions.)
<dt>Make use of AUTOBRIEF.</dt>
<dd>This is highly controversial and the decision to omit <code>\brief</code> here was made largely due to the existing documentation omitting it in most cases. With proper configuration, use of <code>\brief</code> should not be necessary, such that the main argument comes down to aesthetic preference.</dd>
</dl>

Please note that all of the above are *discussion points*. While I have attempted to provide a rationale for the choices shown herein, this is *not* to imply any inflexibility on choosing some other option.

In addition, the following changes that are expected to be fairly non-controversial were made:
- Always insert a blank line between a (previous, unrelated) declaration and documentation.
- Format keywords (`true`, `false`, `const`) as code using the `\c` directive.

## Change Description
Update the documentation in track.h to conform to the new style being proposed. This includes removal of superfluous documentation, consistency improvements, and minor wording improvements.

### CODE REVIEW

**Comment by dstoup** [comment]
This looks great, thank you for putting this together, Matthew ... really appreciate seeing it!

I'm ok with everything here and can go either way regarding Matt's comment about the period. I'm generally in the habit of writing proper sentences when possible adding a period, even in my git commits, which I know some people don't like. I can change habits as needed though.  :)

**Comment by linus-sherrill** [comment]
I can live with the proposed documentation format. As hard as this was to decide on the format, it is a lot easier than actually writing useful, accurate and complete documentation. We should also specify a documentation policy or strategy. I have always tried to provide enough documentation to be able to use the API without having to read the source code. (I don't think I have ever been totally successful, but it is a goal. :-) ) Specifically, the documentation that goes with the abstract algorithm definitions should read like an interface spec since that is what it is. All implementations need to implement the same spec. I'm sure there are other places where this is also an issue.

I agree on removing superfluous docs in the code, but what is obvious to one may not be so for subsequent maintainers. For example `if (m_foo = validate(input) ) { ... }` may not be immediately obvious that this is not a bug. Since this is a valid statement, but not a common idiom in this code base, some documentation would help.

**Comment by mwoehlke-kitware** [comment]
>  I think we should end comments with a period only when it is a complete sentence.

I'm not going to disagree, *exactly*. Rather, what I want to avoid is having documentation that sometimes ends with a period and sometimes doesn't. I'm not *necessarily* a fan, as noted in the proposal, of "unnecessary" articles in brief documentation, but I'd rather have those, and have documentation consistently end with a period, than have a mix of this:
> A special type of track data that redirects to another track
>
> The primary use case for this class [...]

...and this:
> A representation of a track.
>
> A track is a sequence of corresponding identifiers [...]

(Examples maliciously chosen from the original version of `track.h` to illustrate existing inconsistency!)

To me, the former just looks wrong, even though the latter (which *does* have a period) still isn't a proper sentence.

For what it's worth, there's precedent. [Consider](https://doc.qt.io/qt-5/qobject.html#deleteLater):
> Schedules this object for deletion.
>
> The object will be deleted [...]

**Comment by mwoehlke-kitware** [comment]
>  I'm generally in the habit of writing proper sentences when possible adding a period, even in my git commits

*Summaries* should not have periods. *Descriptions* should. This is in fact prescribed by "our" guidelines (n.b. [CONTRIBUTING.rst](https://github.com/Kitware/kwiver/blob/master/CONTRIBUTING.rst#commits))... and by "our" I mean the ones that are generally applied to *any* git repo. (Note that the "for further reading" links are all sources written by folks with no association to KWIVER.)

**Comment by mwoehlke-kitware** [comment]
> We should also specify a documentation policy or strategy.

[Ahem](https://github.com/Kitware/kwiver/blob/master/doc/code-style.rst#api-documentation-doc):
> ## API Documentation: [doc]
>
> This section needs to be written.

Yes. Yes it does. (Need to be written. IOW, wholeheartedly agree!)

> I agree on removing superfluous docs in the code, but what is obvious to one may not be so for subsequent maintainers. For example `if (m_foo = validate(input) ) { ... }` may not be immediately obvious that this is not a bug. Since this is a valid statement, but not a common idiom in this code base, some documentation would help.

Sure, and that's probably not a case of "superfluous". I'm thinking of things like:
```c++
  // Test if the pointer is null
  if( ptr == nullptr )
```

...or:
```c++
  /// Copy constructor
  Foo( Foo const& );
```

A good rule of thumb is that if a comment is just a "word for word" translation of code into prose, it shouldn't exist.

In your above example, two possible comments come to mind:
```c++
  // Attempt to validate and assign the input from the user
  if( m_foo = validate( input ) )
  {
    // Use the validated and newly assigned result
    ...
  }
```

*Both* of the comments are probably excessive, but one or the other would help clarify the intent. I wouldn't classify either of those as superfluous. Per the above examples, *truly* superfluous comments are generally easy to spot, and that point is really aimed squarely at the likes of "default constructor" with no accompanying details. (If it was followed by a detailed description that has useful information, that would be different!)

**Comment by mleotta** [comment]
Okay, I'm fine with using a period at the end of a brief description sentence fragment under the argument that it's industry standard practice to do so (just not the argument that "it's good English") 😉

**Comment by mwoehlke-kitware** [comment]
> Okay, I'm fine with using a period [...] under the argument that it's industry standard practice to do so (just not the argument that "it's good English")

Fair enough :grinning:.

**Pull request merged**
