### PR TITLE
Dev/disable failing sprokit pytests

### PR DESCRIPTION
**Pull request by Erotemic**
Temporarily disables the 3 failing python tests, so we can enable python on Travis-CI (#304).

Info about the three failing tests:

* test-python-pymodules-pythonpath - this is fixed in (#268)
* test-run-pysimple_pipeline-sync - Fails because python processes are used without python threads, which causes the GIL to deadlock. Significant work is needed to fix this issue. The current workaround is to always use the pythread-per-process scheduler when using python processes. 
* test-run-pysimple_pipeline-thread_per_process - same as above

### CODE REVIEW

**Comment by mleotta** [comment]
The same 3 tests fail on the `release` branch.  Can you rebase this on `release` and change the merge target to `release`.  Also you might as well cherry-pick that commit from #304 too so that we can test that Travis CI will pass with this.  I can abandon #304.  Please also make a brief note in `doc/release-notes/release.txt` about disabling broken Python tests.

**Comment by Erotemic** [comment]
Rebased and cherry-picked. Lets see what Travis says...

**Comment by Erotemic** [comment]
Well, clang is failing with a seemingly unrelated error again.

**Comment by Erotemic** [comment]
@mleotta I'm able to reproduce this CI failure consistently on my machine by switching my default compiler to clang.  This happens on both the release branch and this branch. 

When I do a multithreaded make I see this error
```
/home/joncrall/code/fletch/build/install/include/boost/python/object/make_ptr_instance.hpp:30:38: error: no matching function for call
      to 'get_pointer'
        return get_class_object_impl(get_pointer(x));
                                     ^~~~~~~~~~~
```

Seems to be a known issue https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=768569


but on a single threaded make I see this: 
```
[ 48%] Linking CXX executable ../../../tests/bin/test-vxl_triangulate_landmarks
/usr/bin/ld: warning: libjpeg.so.8, needed by /usr/lib/x86_64-linux-gnu/libtiff.so, may conflict with libjpeg.so.62
../../../lib/libkwiver_algo_vxl.so.1.2.0: undefined reference to `vil_image_view<int>::is_a[abi:cxx11]() const'
../../../lib/libkwiver_algo_vxl.so.1.2.0: undefined reference to `vil_image_view<unsigned char>::is_a[abi:cxx11]() const'
../../../lib/libkwiver_algo_vxl.so.1.2.0: undefined reference to `vil_image_view<short>::is_a[abi:cxx11]() const'
../../../lib/libkwiver_algo_vxl.so.1.2.0: undefined reference to `vil_image_view<long>::is_a[abi:cxx11]() const'
../../../lib/libkwiver_algo_vxl.so.1.2.0: undefined reference to `vil_image_view<bool>::is_a[abi:cxx11]() const'
../../../lib/libkwiver_algo_vxl.so.1.2.0: undefined reference to `vil_image_view<unsigned long>::is_a[abi:cxx11]() const'
../../../lib/libkwiver_algo_vxl.so.1.2.0: undefined reference to `vil_image_view<double>::is_a[abi:cxx11]() const'
../../../lib/libkwiver_algo_vxl.so.1.2.0: undefined reference to `vil_image_view<unsigned int>::is_a[abi:cxx11]() const'
../../../lib/libkwiver_algo_vxl.so.1.2.0: undefined reference to `vil_image_view<signed char>::is_a[abi:cxx11]() const'
../../../lib/libkwiver_algo_vxl.so.1.2.0: undefined reference to `vil_image_view<unsigned short>::is_a[abi:cxx11]() const'
../../../lib/libkwiver_algo_vxl.so.1.2.0: undefined reference to `vil_image_view<float>::is_a[abi:cxx11]() const'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
arrows/vxl/tests/CMakeFiles/test-vxl_triangulate_landmarks.dir/build.make:120: recipe for target 'tests/bin/test-vxl_triangulate_landmarks' failed
make[2]: *** [tests/bin/test-vxl_triangulate_landmarks] Error 1
CMakeFiles/Makefile2:2735: recipe for target 'arrows/vxl/tests/CMakeFiles/test-vxl_triangulate_landmarks.dir/all' failed
make[1]: *** [arrows/vxl/tests/CMakeFiles/test-vxl_triangulate_landmarks.dir/all] Error 2
Makefile:162: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by Erotemic** [comment]
I found that the single-threaded error can be fixed by building fletch with clang. 
It seems (unsure about this as the root cause) in the gcc build the symbols is defined as `vil_image_view<int>::is_a() const` but in clang it is defined as `vil_image_view<int>::is_a[abi:cxx11]() const`.

**Comment by Erotemic** [comment]
I modified this to target master, as ideally the new pybind11 stuff will sort out the clang issues.

**Comment by Erotemic** [comment]
I don't think so. I think it can be closed.

**Pull request closed without merging**
